# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: Workflow Conditional Test

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  LICENSE_TEXT: By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

jobs:
  set-release-candidate-true:
    runs-on: ubuntu-latest
    outputs:
      release-candidate-ready: ${{ steps.setOutput.release-candidate-ready}}
    steps:
      - name: Validade license content
        id: setOutput
        run: | 
          echo "::set-output name=release-candidate-ready::true"

  set-release-candidate-false:
    runs-on: ubuntu-latest
    outputs:
      release-candidate-ready: ${{ steps.setOutput.release-candidate-ready}}
    steps:
      - name: Validade license content
        id: setOutput
        run: | 
          echo "::set-output name=release-candidate-ready::false"

  should-run:
    runs-on: ubuntu-latest
    needs: set-release-candidate-true
    if:  needs.set-release-candidate-true.outputs.release-candidate-ready == 'true'
    steps:
      - name: is true
        run: |
          echo "prepping release candidate"
  
  should-not-run:
    runs-on: ubuntu-latest
    needs: set-release-candidate-false
    if:  needs.set-release-candidate-false.outputs.release-candidate-ready == 'true'
    steps:
      - name: is true
        run: |
          echo "prepping release candidate"



