name: noop-one-name

on:
  workflow_dispatch:
  pull_request:
    


permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::616567865305:role/bryaag-collector
          aws-region: us-west-2

      - run: echo winner
        name: done